#!/bin/bash

if [[ "$XDG_CURRENT_DESKTOP" == "Unity" ]]; then
  echo -e "\033[0;32m==>\033[0m Disabling shopping suggestions"
  gsettings set com.canonical.Unity.Lenses disabled-scopes "['more_suggestions-amazon.scope', 'more_suggestions-u1ms.scope', 'more_suggestions-populartracks.scope', 'music-musicstore.scope', 'more_suggestions-ebay.scope', 'more_suggestions-ubuntushop.scope', 'more_suggestions-skimlinks.scope']"
fi
