# Extend path for gems 
export GEM_HOME="$HOME/.local/gems"
export PATH="$HOME/.local/gems/bin:$PATH"

export WORKON_HOME=$HOME/.virtualenvs
export PROJECT_HOME=$HOME/Projects
source /usr/local/bin/virtualenvwrapper.sh
